[project]
name = "future-dynamics"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Nehil Jain", email = "2761999+nehiljain@users.noreply.github.com"},
]
dependencies = [
    "agate==1.7.1",
    "alembic==1.12.1",
    "aniso8601==9.0.1",
    "anyio==4.0.0",
    "attrs==23.1.0",
    "Babel==2.13.1",
    "backoff==2.2.1",
    "certifi==2023.7.22",
    "cffi==1.16.0",
    "charset-normalizer==3.3.2",
    "click==8.1.7",
    "colorama==0.4.6",
    "coloredlogs==14.0",
    "croniter==2.0.1",
    "dagster==1.5.6",
    "dagster-dbt==0.21.6",
    "dagster-duckdb==0.21.6",
    "dagster-embedded-elt==0.21.6",
    "dagster-graphql==1.5.6",
    "dagster-pipes==1.5.6",
    "dagster-webserver==1.5.6",
    "dbt-core==1.6.7",
    "dbt-duckdb==1.6.2",
    "dbt-extractor==0.4.1",
    "dbt-semantic-interfaces==0.2.3",
    "docstring-parser==0.15",
    "duckdb==0.9.1",
    "exceptiongroup==1.1.3",
    "fsspec==2023.10.0",
    "gql==3.4.1",
    "graphene==3.3",
    "graphql-core==3.2.3",
    "graphql-relay==3.2.0",
    "grpcio==1.59.2",
    "grpcio-health-checking==1.59.2",
    "h11==0.14.0",
    "hologram==0.0.16",
    "httptools==0.6.1",
    "humanfriendly==10.0",
    "idna==3.4",
    "importlib-metadata==6.8.0",
    "isodate==0.6.1",
    "Jinja2==3.1.2",
    "jsonschema==4.19.2",
    "jsonschema-specifications==2023.7.1",
    "leather==0.3.4",
    "Logbook==1.5.3",
    "Mako==1.2.4",
    "markdown-it-py==3.0.0",
    "MarkupSafe==2.1.3",
    "mashumaro==3.8.1",
    "mdurl==0.1.2",
    "minimal-snowplow-tracker==0.0.2",
    "more-itertools==8.14.0",
    "msgpack==1.0.7",
    "multidict==6.0.4",
    "networkx==3.2.1",
    "numpy==1.26.1",
    "orjson==3.9.10",
    "packaging==23.2",
    "parsedatetime==2.6",
    "pathspec==0.11.2",
    "pendulum==2.1.2",
    "polars==0.19.12",
    "protobuf==4.25.0",
    "pyarrow==14.0.0",
    "pycparser==2.21",
    "pydantic==1.10.13",
    "Pygments==2.16.1",
    "python-dateutil==2.8.2",
    "python-dotenv==1.0.0",
    "python-slugify==8.0.1",
    "pytimeparse==1.1.8",
    "pytz==2023.3.post1",
    "pytzdata==2020.1",
    "PyYAML==6.0.1",
    "referencing==0.30.2",
    "requests==2.31.0",
    "requests-toolbelt==0.10.1",
    "rich==13.6.0",
    "rpds-py==0.12.0",
    "six==1.16.0",
    "sling==1.0.55",
    "sniffio==1.3.0",
    "SQLAlchemy==2.0.23",
    "sqlparse==0.4.4",
    "starlette==0.32.0",
    "tabulate==0.9.0",
    "text-unidecode==1.3",
    "tomli==2.0.1",
    "toposort==1.10",
    "tqdm==4.66.1",
    "typer==0.9.0",
    "typing-extensions==4.8.0",
    "universal-pathlib==0.1.4",
    "urllib3==1.26.18",
    "uvicorn==0.24.0",
    "uvloop==0.19.0",
    "watchdog==3.0.0",
    "watchfiles==0.21.0",
    "websockets==12.0",
    "yarl==1.9.2",
    "zipp==3.17.0",
]
requires-python = "==3.10.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
package-type = "application"

[tool.dagster]
module_name = "opensource_mds"